server:
  port: 8001

spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mariadb://localhost:3305/db_user
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
